import { defineConfig } from '@playwright/test'

/**
 * Minimal Playwright config for tests generated by the KayScope Test Builder UI.
 * - No authentication setup required
 * - No project matrix — runs as a single default project
 * - Reuses the already-running dev server
 */
export default defineConfig({
  testDir: 'tests/e2e/generated',
  timeout: 30_000,
  retries: 0,
  reporter: 'json',         // JSON goes to stdout — captured by the API route
  workers: 1,

  use: {
    baseURL: process.env.NEXTAUTH_URL ?? 'http://localhost:3000',
    headless: true,
    screenshot: 'only-on-failure',
    video: 'off',
  },

  // No webServer block — generated tests typically target external URLs.
  // If you need to test localhost, start the dev server manually first.
})
